import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { PropsWithChildren } from 'react';

import { LocaleParam } from '@theasset/internationalization/domain';
import { useLocale } from '@theasset/internationalization/hooks';
import { I18nProvider } from '@theasset/internationalization/ui';

import '@theasset/style-system/global.css';

const GeistSans = localFont({
	src: '../fonts/GeistVF.woff',
	variable: '--font-geist-sans'
});
const GeistMono = localFont({
	src: '../fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const RootLayout = async ({ children, params: { lang } }: PropsWithChildren<LocaleParam>) => {
	const locales = await useLocale();

	return (
		<html lang={lang} className={`${GeistSans.variable} ${GeistMono.variable}`}>
			<I18nProvider locales={locales} currentLanguage={lang}>
				<body>{children}</body>
			</I18nProvider>
		</html>
	);
};

export default RootLayout;
