import { PropsWithChildren } from 'react';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';

import { LocaleParam } from '@theasset/internationalization/domain/locale-param';
import { useLocale } from '@theasset/internationalization/hooks/use-locale';
import { I18nProvider } from '@theasset/internationalization/ui/i18n-provider';
import '@theasset/style-system/global.css';
import { ToastGlobalRegion } from '@theasset/ui/toast';

const GeistSans = localFont({
	src: '../fonts/GeistVF.woff',
	variable: '--font-geist-sans'
});
const GeistMono = localFont({
	src: '../fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const RootLayout = async ({ children, params: { lang } }: PropsWithChildren<LocaleParam>) => {
	const locales = await useLocale();

	return (
		<html lang={lang} className={`${GeistSans.variable} ${GeistMono.variable}`}>
			<I18nProvider locales={locales} currentLanguage={lang}>
				<body>
					{children}
					<ToastGlobalRegion />
					<SpeedInsights />
				</body>
			</I18nProvider>

			<Analytics />
		</html>
	);
};

export default RootLayout;
